---
-
  hosts: linode1
  gather_facts: false

  tasks:
    - name: ping
      ping:
    
     - name: install hugo
      apt:
        name: hugo
        update_cache: yes
        state: latest
   
     - name: install git
      apt:
        name: git
        update_cache: yes
        state: latest

    - name: clone repo
      git:
        repo: https://github.com/unpass/nate.unpass.net.git
        dest: "/home/unpass/blog/unpass"
        force: yes
        version: master

     - name: install rsync
      apt:
        name: rsync
        update_cache: yes
        state: latest

    - name: sync theme
      synchronize:
        src: "unpass/themes/hugo-bearblog"
        dest: "/home/unpass/blog/unpass/themes/hugo-bearblog"
        recursive: true
        delete: true # Clean up extra files that may occur from recursive: true

     - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest


     - name: copy nginx.conf
      copy:
        src: "/etc/nginx/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        mode: 0644 

    - name: remove default nginx site
      file:
        name: "/etc/nginx/sites-enabled/default"
        state: absent
    
    - name: copy /etc/nginx/sites-available/nate from local
      copy:
        src: "/etc/nginx/sites-available/nate"
        dest: "/etc/nginx/sites-available/nate"
        mode: 0644

    - name: create nginx symlink
      file:
        src: "/etc/nginx/sites-available/nate"
        dest: "/etc/nginx/sites-enabled/nate"
        state: link

    # - name: run hugo server (tcp/1313)
    # shell:
    # cmd: hugo server -t hugo-bearblog --buildDrafts --bind "0.0.0.0"
    # chdir: "/home/unpass/blog/unpass" 
    
    - name: update nginx sites-available (hugo)
      shell:
        cmd: hugo
        chdir: "/home/unpass/blog/unpass"

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: install certbot
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: latest

    - name: generate certs
      shell: certbot --nginx -d 'nate.unpass.net' -m hello@unpass.net --agree-tos -n --nginx-ctl '/usr/sbin/nginx' --redirect

     - name: restart nginx
       service:
         name: nginx
         state: restarted

...
